services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: bigmi-homeassistant
    restart: unless-stopped
    ports:
      - "8123:8123"
    environment:
      TZ: Asia/Hong_Kong
    volumes:
      - ./ha:/config

  appdaemon:
    image: acockburn/appdaemon:latest
    container_name: bigmi-appdaemon
    restart: unless-stopped
    profiles:
      - studio
    depends_on:
      - homeassistant
    ports:
      - "5050:5050"
    environment:
      HA_URL: http://homeassistant:8123
      TOKEN: ${HA_TOKEN:-replace-me}
    volumes:
      - ./appdaemon/conf:/conf
